on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: oisinaks.azurecr.io
        username: ${{ secrets.acr_oisinaks_username }}
        password: ${{ secrets.acr_oisinaks_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t oisinaks.azurecr.io/oisinakscluster:${{ github.sha }}
        docker push oisinaks.azurecr.io/oisinakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_oisinakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep oisinakscluster40e9 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace oisinakscluster40e9`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: oisinakscluster40e9
        container-registry-url: oisinaks.azurecr.io
        container-registry-username: ${{ secrets.acr_oisinaks_username }}
        container-registry-password: ${{ secrets.acr_oisinaks_password }}
        secret-name: oisinaksclusdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: oisinakscluster40e9
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          oisinaks.azurecr.io/oisinakscluster:${{ github.sha }}
        imagepullsecrets: |
          oisinaksclusdockerauth